[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Redirect rules
[[redirects]]
  from = "/admin.html"
  to = "/dashboard/admin"
  status = 301

[[redirects]]
  from = "/health"
  to = "/api/health"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://obdoc.co.kr"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment-specific settings
[context.production]
  command = "npm run build"
  
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.deploy-preview]
  command = "npm run build"
  
[context.deploy-preview.environment]
  NODE_ENV = "preview"
  NEXT_TELEMETRY_DISABLED = "1"

[context.branch-deploy]
  command = "npm run build"
  
[context.branch-deploy.environment]
  NODE_ENV = "development"
  NEXT_TELEMETRY_DISABLED = "1"
